version: "3"
services:
  node:
    container_name: node
    image: atoris1192/node:0.1.6
    volumes:
      - ./app:/node/app
    ports:
      - "1234:1234"
      - "1235:1235"
    working_dir: /node
    # command: cp -rp /tmp/app /node
    # command: npx parcel --hmr-port 1235 --hmr-hostname localhost index.pug
    tty: true